import os
import yaml
import json


def load_config(path="envsync.yaml"):
    with open(path, "r") as f:
        config = yaml.safe_load(f)
    if not config.get("source_of_truth"):
        config["source_of_truth"] = ".env.example"
    if not config.get("snapshots"):
        config["snapshots"] = {"directory": ".envsync/snapshots", "max_keep": 10, "encrypted": True}
    return config


def load_environment(config, env_name):
    environments = config.get("environments", {})
    if env_name not in environments:
        raise ValueError(f"Environment '{env_name}' not defined in envsync.yaml")
    
    env_config = environments[env_name]
    env_type = env_config.get("type", "file")
    
    if env_type == "file":
        path = env_config.get("path")
        fmt = env_config.get("format", "dotenv")
        return load_from_file(path, fmt)
    else:
        raise ValueError(f"Unsupported environment type: {env_type}")


def load_source_of_truth(config):
    path = config.get("source_of_truth", ".env.example")
    return load_from_file(path, "dotenv")


def load_from_file(path, fmt="dotenv"):
    if not os.path.exists(path):
        raise FileNotFoundError(f"File not found: {path}")
    
    with open(path, "r") as f:
        content = f.read()

    ext = os.path.splitext(path)[1].lower()
    if fmt == "yaml" or ext in [".yaml", ".yml"]:
        return parse_yaml_env(content)
    elif fmt == "json" or ext == ".json":
        return parse_json_env(content)
    else:
        return parse_dotenv(content)


def parse_dotenv(content):
    result = {}
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        result[key] = value
    return result


def parse_yaml_env(content):
    raw = yaml.safe_load(content) or {}
    return {k: str(v) for k, v in raw.items()}


def parse_json_env(content):
    raw = json.loads(content)
    return {k: str(v) for k, v in raw.items()}


def write_environment(config, env_name, kv):
    environments = config.get("environments", {})
    if env_name not in environments:
        raise ValueError(f"Environment '{env_name}' not found")
    env_config = environments[env_name]
    path = env_config.get("path")
    write_dotenv(path, kv)


def write_dotenv(path, kv):
    with open(path, "w") as f:
        f.write("# Generated by envsync\n")
        for k, v in kv.items():
            if any(c in v for c in [" ", "\t", "#", '"', "'"]):
                f.write(f'{k}="{v}"\n')
            else:
                f.write(f"{k}={v}\n")


def scaffold_config(path="envsync.yaml"):
    template = """# envsync.yaml
version: "1"
source_of_truth: .env.example

environments:
  dev:
    type: file
    path: .env.dev
    format: dotenv
  staging:
    type: file
    path: .env.staging
    format: dotenv
  production:
    type: file
    path: .env.production
    format: dotenv

runtimes:
  node: "20"
  python: "3.11"

secrets:
  encryption_key_env: ENVSYNC_KEY
  redacted_keys:
    - PASSWORD
    - SECRET
    - TOKEN
    - KEY
    - PRIVATE

snapshots:
  directory: .envsync/snapshots
  max_keep: 10
  encrypted: true
"""
    with open(path, "w") as f:
        f.write(template)
        

